spring:
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html

  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  web:
    resources:
      add-mappings: true
      cache:
        period: 3600
      chain:
        enabled: true
        cache: true
        compressed: true
      static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.learning.seckill.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
